package custom_memo.dev.back.common.exception

class CommonException(val errorCode: ErrorCode) : RuntimeException() {
}
